# This is a basic workflow to help you get started with Actions

name: laab1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: cr.yandex/crpg9q8s45a94mlu6opi
        username: oauth
        password: AQAAAAAHNn-YAATuwUNpq3LlC0DepQccXIudX5M  
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: laab1
        registry: cr.yandex/crpg9q8s45a94mlu6opi
